# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Siju"                                # Your name
  description: "A computer enthusiast  "   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Academic Sessions"
        href: projects/index.qmd
      - text: "ICT"
        href: photography/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: folder-symlink
        href: https://bookdown.org/siju_swamy/Stat_Lab/
      - icon: linkedin
        href: https://www.linkedin.com/in/siju-swamy/
      - icon: envelope
        aria-label: email
        href: "mailto:sijuswamy@gmail.com"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Siju Swamy CC BY-SA 4.0</span>
    center: |
      <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">View tutorial on R programming!</a></span>
    right: |
      <span class="faux-block"><a href="https://github.com/sijuswamy/">View repositories on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 3848
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true